# -*- coding: utf-8 -*-
"""lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1Ymb_zCfus6kHHJup-lFCFgcrdxaoUw
"""

#create a list of 10 integer

numbers = [10, 23, 5,89,45,67,34,22,11,90]
print('orignal List ',numbers)


#sum max, and min

print('sum',sum(numbers))
print('max',max(numbers))
print('min',min(numbers))

#add and remove element
numbers.append(50)
numbers.remove(23)
print('updated list:', numbers)

#sort ascending and decending

print('ascending',sorted(numbers))
print('decending',sorted(numbers, reverse=True))


#create tuples

fruits=('apple','banana','cherry','mango','graps')
print('second element:',fruits[1])
print('last element:',fruits[-1])


#convert tuples into list

fruit_list=list(fruits)
fruit_list[2]='orang'
print('Modified List:',fruit_list)



#create sets

set_a={1,2,3,4,5}
set_b={4,5,6,7,8}

#union, intersection,diffrence

print('union',set_a & set_b)
print('intersection',set_a & set_b)
print('diffrence',set_a & set_b)