# -*- coding: utf-8 -*-
"""Resultreproduced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12InnQOrwH-su8pexc7nwowURaZhiuCys
"""

import numpy as np

# Create 1D array
arr = np.arange(1, 21)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(21, 41)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)


import matplotlib.pyplot as plt

# Line Plot
x = list(range(1, 10))
y = [i**2 for i in x]
plt.plot(x, y)
plt.title('Numbers vs Squares')
plt.xlabel('Numbers')
plt.ylabel('Squares')
plt.show()

# Bar Chart
students = ['hamza', 'abbas ', 'Ahmed', 'shehzad',]
marks = [80, 70, 68, 92, ]
plt.bar(students, marks)
plt.title('Student Marks')
plt.xlabel('Students')
plt.ylabel('Marks')
plt.show()

# Pie Chart
categories = ['Category A', 'Category B', 'Category C']
values = [33.3, 33.3, 33.3]
plt.pie(values, labels=categories, autopct='%1.1f%%')
plt.title('Category Distribution')
plt.show()